### ISSUE TITLE
Problem with Generate samples

### ISSUE THREAD

**Issue by KrisRousseau** [PhenotypeFoundation/PhenotypeDatabase#159]
Hello,
I'm a new user of the Phenotype Database  and I don't succeed to generate samples after design my study. I've got the mail : "Failure in generating samples. Please try again."
No more information about what could be wrong.
Any idea ?

Best regards.
Christine ROUSSEAU

**Comment by ferryjagers** [comment]
I just released an update that should address this issue

**Comment by KrisRousseau** [comment]
Thanks, it works now.
