### ISSUE TITLE
Problems with creating platforms for the tutorial intervention study

### ISSUE THREAD

**Issue by mikkeltullin** [PhenotypeFoundation/PhenotypeDatabase#160]
Hi, 
I am facing problems when I am trying to create a platform in the genetic variation. 

First it looks like this: 
![before creating](https://cloud.githubusercontent.com/assets/22052329/18828757/7f0582ea-83d9-11e6-8899-c3557e559623.PNG)
 
And then I get this error message:
![creating a platform for tutorial interventioin study](https://cloud.githubusercontent.com/assets/22052329/18828778/a1ba2b9c-83d9-11e6-9e79-86c70fced6e8.PNG)

Best 
Mikkel Tullin

**Comment by ferryjagers** [comment]
Were you working on dashin.eu/interventionstudies-test or dashin.eu/interventionstudies all along?
There was a misconfiguration in our test instance that caused a redirection to production when switching modules. If you were working on the test instance please try again now

**Comment by mikkeltullin** [comment]
I was only workin on dashin.eu/interventionstudies. I have just tried again but with no luck...

**Comment by ferryjagers** [comment]
The platform 'Genetics tutorial' already exists, platform names must be unique.
This should be given as feedback but contained an error causing the Grails Runtime Exception you encountered.

I tried to reproduce it but not with the same name, my bad.
It will be fixed in the next release!

**Comment by mikkeltullin** [comment]
Ok
