### ISSUE TITLE
Impossible to create a field with "term for ontology" type

### ISSUE THREAD

**Issue by KrisRousseau** [PhenotypeFoundation/PhenotypeDatabase#162]
I installed dbNp on a local server
This installation seems to work, 
But I didn't succeed to create a new file in a template with "term for ontology" type.

Steps:
- add/modify study template
- create a new file
- Select "term for ontology" for the type of the new file
- click add new ontologie
- type "NCBITAXON"

Ontology term is well retrieved but the dropdown is displayed under the popup window and not accessible to select.

did I do something wrong?

**Comment by ferryjagers** [comment]
Just to be clear; you are not able to select '(NCBITAXON) National....'  as I do below?

<img width="1109" alt="templatefield selection of terms ncbitaxon selection" src="https://cloud.githubusercontent.com/assets/1736833/18990871/4e5ed094-8715-11e6-8663-55a7dde61c57.png">

**Comment by KrisRousseau** [comment]
Yes. I do the same, but the choice "(NCBITAXON) ...." appears desactivated (grayed uder the window).
A problem with the navigator ? I use Firefox.

**Comment by ferryjagers** [comment]
I think you closed the issue on accident?
For me it also works when I use Firefox (49.0.1, on OSX 10.12).
Could you please try to reproduce your problem on dashin.eu/interventionstudies-test (u: user p: useR123!) and come back to me with the result?

**Comment by KrisRousseau** [comment]
I have the same result as in local (firefox 49.0.1 on Windows10).

**Comment by KrisRousseau** [comment]
It works fine now. No rational explanation.
So I close the issue.
