### ISSUE TITLE
publicassay to false ?

### ISSUE THREAD

**Issue by KrisRousseau** [PhenotypeFoundation/PhenotypeDatabase#178]
Hi,
If I select a study and go to assays list, I can see the list of assays and if there is a public access or not (publicassay column). But if the the column "publicassay" is true or false, when I click on the link "details", I access to the datas.
So, what does mean publicassay = false ?
What should I do to open access only to the design ?

Thanks for your help.
Kris

**Comment by ferryjagers** [comment]
Thank you for reporting! Fixed in 81ffcbcfd4f7f044cc858db0b7598660826a77d7
