### ISSUE TITLE
I can not sign up

### ISSUE THREAD

**Issue by dygdedesener** [PhenotypeFoundation/PhenotypeDatabase#200]
I have registered with the user name duygu and mail address d.dedesener@maastrichtuniversity.nl. Then I got a confirmation mail and I confirmed it but still waiting for approval before logging. I would be glad if you can help.

**Comment by ferryjagers** [comment]
Hi Duygu,

I just sent you an e-mail with an explanation and (hopefully) a solution.

Best,
Ferry
